_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  ban: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  custom_update_file: 0
  datetime: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  glazed_builder_block: 0
  glazed_builder_page: 0
  glazed_helper: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  insert_block: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_tabs: 0
  lightning_core: 0
  lightning_media: 0
  lightning_media_audio: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_slideshow: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_roles: 0
  link: 0
  media: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  owlcarousel: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quicktabs: 0
  quicktabs_accordion: 0
  quicktabs_jqueryui: 0
  rdf: 0
  search: 0
  shortcode: 0
  shortcode_basic_tags: 0
  shortcode_example: 0
  shortcut: 0
  slick: 0
  slick_entityreference: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_accordion: 0
  views_dates: 0
  views_menu_children_filter: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  views: 10
  paragraphs: 11
  glazed_builder: 100
  standard: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  glazed: 0
  stable: 0
  classy: 0
  bootstrap4: 0
  glazed_subtheme: 0
profile: standard
