<?Php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;
use Drupal\file\FileInterface;
use Drupal\file\Entity\File;
use Drupal\Component\FileSecurity\FileSecurity;
use Drupal\Component\FileSystem\FileSystem as ComponentFileSystem;
use Drupal\Component\Utility\Environment;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\File\Exception\FileException;
use Drupal\Core\File\Exception\FileWriteException;
use Drupal\Core\File\FileSystem;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;


function tcgcustom_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    //die('hg');
    // $options = array(
    //     'US' => 'US',
    //   );
       //if($form_id=='node_listing_event_edit_form'){
        //    die();
       // $form['field_address']['country_code']['#default_value'] = 'US';
       //} 
}

function tcgcustom_menu_children_filter_join_prefix_alter(array &$prefixes) {
  $prefixes[] = 'internal:/node/';
}